repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: '^.*\.ipynb$'
      - id: end-of-file-fixer
        exclude: '^.*\.ipynb$'

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.6
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        exclude: '^.*\.ipynb$'
      - id: ruff-format
        exclude: '^.*\.ipynb$'

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        additional_dependencies: ["types-pyyaml", "types-requests"]
        exclude: '^.*\.ipynb$'

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.0
    hooks:
      - id: codespell
        args: [--ignore-words-list=rouge]
        exclude: '^.*\.ipynb$'
